version: 2.1

orbs:
  terraform: circleci/terraform@2.0.0
  aws: circleci/aws@2.0.0

executors:
  ubuntu:
    machine:
      image: ubuntu-2204:current

jobs:
  terraform:
    executor: ubuntu
    steps:
      - checkout  # Check out your source code
      
      - aws/configure-aws-credentials:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          aws_region: YOUR_AWS_REGION

      - terraform/init:
          - run:
            name: init and plan
            command: |
              terraform init

      - terraform/plan:
        - run:
            name: init and plan
            command: |
              terraform plan

      - terraform/apply:
          - run:
              name: apply
              command: |
                terraform apply --auto-approve
          # auto_approve: true  # Automatically approve the apply

workflows:
  version: 2
  terraform:
    jobs:
      - terraform
            
# version: 2.1
# orbs:
#   base-packages: twdps/base-packages@0.1.3

# jobs:
#   setup-credentials:
#     docker:
#       - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
#     steps:
#       - run:
#           name: Configure AWS Credentials
#           command: |
#             mkdir -p ~/.aws
#             echo "[default]" > ~/.aws/credentials
#             echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
#             echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

#   plan-apply:
#     docker:
#       - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
#     steps:
#       - checkout
#       - run:
#           name: terraform init & plan
#           command: |
#             terraform init 
#             terraform plan
#       - persist_to_workspace:
#           root: .
#           paths:
#             - .  # Specify what to persist

#   apply:
#     docker:
#       - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
#     steps:
#       - attach_workspace:
#           at: /workspace
#       - run:
#           name: terraform apply
#           command: |
#             cd /workspace  # Ensure you're in the correct directory
#             terraform apply -auto-approve
#       - persist_to_workspace:
#           root: /workspace
#           paths:
#             - .  # Specify what to persist

# workflows:
#   plan_approve_apply:
#     jobs:
#       - setup-credentials
#       - plan-apply:
#           requires:
#             - setup-credentials
#       - hold-apply:
#           type: approval
#           requires:
#             - plan-apply
      # - apply:
      #     requires:
      #       - hold-apply
